### ISSUE TITLE
GTE and LTE are inverted

### ISSUE THREAD

**Issue by jcornaz** [optimatika/okAlgo#4]
"GTE" means "Greater Than or Equals" ('>=') and "LTE" means "Lesser Than or Equals" ('<=') right?

So in `x >= C`, C is a *lower* bound and in `x <= C`, C is an *upper* bound right?

But currently okAlgo does the inverse:
```kotlin
infix fun GTE(number: Int): ExpressionBuilder {
    items += { upper(number) }
    return this
}

infix fun LTE(number: Int): ExpressionBuilder {
    items += { lower(number) }
    return this
}
```

**Comment by thomasnield** [comment]
That might be an issue, I'll check it as soon as possible. Feel free to put in a PR if you want to beat me.
