### ISSUE TITLE
local build and jitpack integration are broken

### ISSUE THREAD

**Issue by holgerbrandl** [optimatika/okAlgo#6]
Hey @thomasnield, currently the build fails locally and on jitpack.io (see https://jitpack.io/#optimatika/okAlgo) with:

```
[okAlgo]$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/brandl/Desktop/okAlgo/build.gradle' line: 64

* What went wrong:
A problem occurred evaluating root project 'okAlgo'.
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
[okAlgo]$ 

```

**Comment by thomasnield** [comment]
Yeah, I'm going to see if there's a way around that. For now, I'd recommend using the releases. I need to get a third one out soon so #3 can start getting used.

**Comment by thomasnield** [comment]
FYI, source code is easy to copy into a personal project. There are only two source code files.

**Comment by thomasnield** [comment]
@holgerbrandl Alright, I fixed the build, including for JitPack. Forgot to disable my signing tasks in the Gradle script.

**Comment by holgerbrandl** [comment]
Awesome thanks. Works perfectly now
